# Generated by Django 5.2.7 on 2025-10-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Products',
        ),
    ]
